
services:
    phpdoc:
        container_name: testv_php
        restart: always
        build: 
            context: ./image/
            #args:
            #    - PHP_FOLDER_PROJECT=/var/www
            #    - VALUE_PHP_VERSION=8.3.7RC1-fpm
            #    - VALUE_XDEBUG_VERSION=3.3.2
            #    - VALUE_COMPOSER_VERSION=2.7.4
            #    - VALUE_MHSEND_VERSION=v0.2.0
        volumes:
            - ./www/:/usr/local/apache2/www
            - ./docs/:/usr/local/apache2/docs
            - ./phpdoc.xml:/var/docker/phpdoc/phpdoc.xml

