
services:
    phpdoc:
        container_name: testv_phpdoc
        restart: always
        build: 
            context: ./image/
            #args:
            #    - DEF_PHPDOC_VERSION=latest
        volumes:
            - ./www/:/usr/local/apache2/www
            - ./docs/:/usr/local/apache2/docs
            - ./phpdoc.xml:/var/docker/phpdoc/phpdoc.xml

